name: Create Issue from Commit

on:
  push:
    branches:
      - main  # Adjust this to your main branch name or other desired branches

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Issue
        run: |
          TOKEN="${{ secrets.ACCESS_TOKEN }}"
          REPO_URL="https://api.github.com/repos/${{ github.repository }}"
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          
          curl -X POST -H "Authorization: token $TOKEN" -d "{\"title\":\"New Issue from Commit\", \"body\":\"Commit Message: $COMMIT_MESSAGE\"}" $REPO_URL/issues
