name: Create Issue from Commit

on:
  push:
    branches:
      - main  # Adjust this to your main branch name or other desired branches
permissions:
  contents: read
  issues: write 
jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Issue
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO_URL="https://api.github.com/repos/${{ github.repository }}"
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          ISSUE_BODY="- [ ] $COMMIT_MESSAGE \n- [ ] ppp\n- [ ] 000"
          
          curl -X POST -H "Authorization: token $TOKEN" -d "{\"title\":\"$COMMIT_MESSAGE\", \"body\":\"$ISSUE_BODY\"}" $REPO_URL/issues
